### ISSUE TITLE
Question about offsetting 0 value.

### ISSUE THREAD

**Issue by Guacore** [oliviaguest/gini#1]
Hi Olivia,
Regard to this line `array += 0.0000001`
Is there a particular reason using 0.0000001 and not some smaller positive number, such as `np.nextafter(np.float64(0), np.float64(1))`?

Also, why not first check if a zero exists in the array before adding 0.0000001?

**Comment by oliviaguest** [comment]
Feel free to propose an edit. I didn't want to add an if statement, but by all means replace it with something from numpy.

**Comment by mu578** [comment]
@Guacore @oliviaguest , normalizing and shifting the range 

```
def gini(a, e = 0.0000001):
	a = a.flatten()
	a = np.sort(a)
# edit: logically min should be a[0] and max a[n - 1]
	a = np.interp(a, (a.min(), a.max()), (0.0 + e, 1.0 + e))
	n = a.shape[0]
	i = np.arange(1, n + 1)
	return ((np.sum((2 * i - n - 1) * a)) / ((n * np.sum(a))))
```

**Comment by oliviaguest** [comment]
Nice one @moe123 — wanna set up a PR?

**Comment by mu578** [comment]
@oliviaguest thx,
however, I don't think a pull request is necessary. For doing such, it would ask much more work i.e to prevent unnecessary  copies and surely minimizing the number of iterations/operations such as  `(2 * i - n - 1) * a)` should be computed in-place in a single shot same for sort and normalization operation  could be performed in a single loop construct and surely `insitu`.

My quick suggestion only answer to the op question, how to transpose the data in a strictly positive definite space ; there are maybe more (mathematically speaking) acceptable ways to handle it 8-).

You have a nice day.

**Comment by mu578** [comment]
Hello @oliviaguest and @Guacore,

First, my apologies for the late answer, I wanted to add up yesterday but 
unfortunately did not have a second (so did it over my train ride).

Now, let's talk away and about if we could find a more accurate acceptable
generalized approach. Sure, if you agree to, hence, leaving the world of
software implementation which is not really intellectually nourishing.

Taking a conceptual and contextual approach:

-- let's say we have an agnostic classifier no matter the underlaying algorithm.
-- let's say this classifier has online training / fitting capabilities.
-- let's say you want to implement an indicator for data-rejection, somehow new 
   data don't carry enough relevant informations for your problem and will weaken
   your model; because of some kind of false correlation, irrelevant redundancies,
   free candies away issues: blah-blah and blah...

would you not want to take account of your NNZ (non-zero) v. Z population (i.e density) while trying
scoring / qualifying / probing your new model, maybe by implementing some kind
of error function while computing your indicator? a self-indicator control?
